export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_PROJECTS_FULFILLED = "FETCH_PROJECTS_FULFILLED";
export const FETCH_PROJECTS_REJECTED = "FETCH_PROJECTS_REJECTED";
export const FETCH_PROJECTS_PENDING = "FETCH_PROJECTS_PENDING";

export const FETCH_PROJECT = "FETCH_PROJECT";
export const FETCH_PROJECT_FULFILLED = "FETCH_PROJECT_FULFILLED";
export const FETCH_PROJECT_REJECTED = "FETCH_PROJECT_REJECTED";
export const FETCH_PROJECT_PENDING = "FETCH_PROJECT_PENDING";

export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_FULFILLED = "DELETE_PROJECT_FULFILLED";
export const DELETE_PROJECT_REJECTED = "DELETE_PROJECT_REJECTED";
export const DELETE_PROJECT_PENDING = "DELETE_PROJECT_PENDING";

export const CREATE_PROJECT = "CREATE_PROJECT";

export const UPDATE_PROJECT = "UPDATE_PROJECT";
